# Hadolint configuration
# https://github.com/hadolint/hadolint#configure
ignored:
  # Don't require pinning system packages in apk add / apt-get install.
  # Dev container images intentionally use latest OS packages.
  - DL3008 # apt-get: pin versions
  - DL3018 # apk: pin versions

  # wget is used intentionally for downloading release binaries;
  # ralphex-fe uses curl (bun install script) + wget (Hugo binary download).
  - DL3047 # avoid using wget; use curl
  - DL4001 # either use wget or curl, not both

  # pipefail SHELL not required — only one pipe exists (bun install)
  # and curl -f already fails on HTTP errors.
  - DL4006 # set SHELL option -o pipefail before RUN with pipe

  # SNIPPET variable in devcontainer-claude-bun follows the official
  # Anthropic Claude Code devcontainer pattern (anthropics/claude-code).
  - SC2034 # variable appears unused

  # Pipes inside command substitutions (e.g. grep | cut) are intentional;
  # empty results are explicitly checked afterwards.
  - SC2312 # pipe in command substitution masks return value
